# Generated by Django 4.2.21 on 2025-06-24 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data_nascimento", models.DateField()),
                (
                    "sexo",
                    models.CharField(
                        choices=[("Masculino", "Masculino"), ("Feminino", "Feminino")],
                        max_length=10,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pacientes_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fisioterapeuta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pacientes_fisioterapeuta",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
