# Generated by Django 4.2.21 on 2025-06-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="diagnostico",
            field=models.TextField(blank=True),
        ),
    ]
