# Generated by Django 4.2.21 on 2025-07-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avaliacoes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="avaliacao",
            old_name="profissional",
            new_name="fisioterapeuta",
        ),
        migrations.RemoveField(
            model_name="avaliacao",
            name="conteudo",
        ),
        migrations.AddField(
            model_name="avaliacao",
            name="area",
            field=models.CharField(default="Membro Superior", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="avaliacao",
            name="articulacao",
            field=models.CharField(default="Ombro", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="avaliacao",
            name="medidas_json",
            field=models.TextField(default={}),
            preserve_default=False,
        ),
    ]
