# Generated by Django 4.2.21 on 2025-06-28 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0002_paciente_diagnostico"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("evolucoes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evolucao",
            name="autor",
        ),
        migrations.RemoveField(
            model_name="evolucao",
            name="descricao",
        ),
        migrations.AddField(
            model_name="evolucao",
            name="fisioterapeuta",
            field=models.ForeignKey(
                default=2,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evolucao",
            name="texto",
            field=models.TextField(default="Sem descrição"),
        ),
        migrations.AlterField(
            model_name="evolucao",
            name="paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pacientes.paciente"
            ),
        ),
    ]
