# Generated by Django 4.2.21 on 2025-06-30 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("evolucoes", "0002_remove_evolucao_autor_remove_evolucao_descricao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evolucao",
            name="data_edicao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evolucao",
            name="editado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="evolucao",
            name="versao_original",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versoes",
                to="evolucoes.evolucao",
            ),
        ),
        migrations.AlterField(
            model_name="evolucao",
            name="data",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="evolucao",
            name="fisioterapeuta",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="evolucao",
            name="texto",
            field=models.TextField(),
        ),
    ]
