# Generated by Django 4.2.21 on 2025-06-30 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0002_paciente_diagnostico"),
        ("evolucoes", "0003_evolucao_data_edicao_evolucao_editado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evolucao",
            name="paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evolucoes",
                to="pacientes.paciente",
            ),
        ),
    ]
