# Generated by Django 4.2.21 on 2025-07-10 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pacientes", "0002_paciente_diagnostico"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("hora_inicio", models.TimeField()),
                ("hora_fim", models.TimeField()),
                (
                    "tipo_atendimento",
                    models.CharField(
                        choices=[
                            ("motor", "Fisioterapia Motora"),
                            ("respiratoria", "Fisioterapia Respiratória"),
                            ("neurologica", "Fisioterapia Neurológica"),
                            ("avaliacao", "Avaliação"),
                        ],
                        default="motor",
                        max_length=100,
                    ),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "fisioterapeuta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agendamentos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agendamentos",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agendamento",
                "verbose_name_plural": "Agendamentos",
                "ordering": ["data", "hora_inicio"],
            },
        ),
    ]
